-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

ALTER TABLE public.events
  ALTER COLUMN content TYPE jsonb USING content::jsonb;

CREATE TYPE public."INVITATION_STATUS" AS ENUM (
  'pending',
  'accepted',
  'rejected'
);

CREATE TABLE public.event_grading_criteria (
  id                uuid                     DEFAULT gen_random_uuid() NOT NULL,
  created_at        timestamp with time zone DEFAULT now() NOT NULL,
  event_id          uuid                     DEFAULT gen_random_uuid(),
  name              text                     DEFAULT gen_random_uuid(),
  short_description text
);

ALTER TABLE public.event_grading_criteria
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.event_grading_criteria
  ADD CONSTRAINT event_grading_criteria_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.event_grading_criteria
  ADD CONSTRAINT event_grading_criteria_pkey PRIMARY KEY (id);

GRANT ALL ON public.event_grading_criteria TO anon;

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.event_grading_criteria TO authenticated;

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.event_grading_criteria TO service_role;

CREATE POLICY "Enable delete for users based on user_id" ON public.event_grading_criteria
  FOR DELETE
  USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON public.event_grading_criteria
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON public.event_grading_criteria
  FOR SELECT
  USING (true);

CREATE POLICY "Policy with table joins" ON public.event_grading_criteria
  FOR UPDATE
  USING (true);

ALTER TABLE public.events
  ADD COLUMN poster_path text;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.events TO anon;

CREATE TABLE public.group_members (
  id         uuid                     DEFAULT gen_random_uuid() NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  group_id   uuid                     DEFAULT gen_random_uuid(),
  member_id  uuid                     DEFAULT gen_random_uuid()
);

ALTER TABLE public.group_members
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.group_members
  ADD CONSTRAINT group_members_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.group_members
  ADD CONSTRAINT group_members_pkey PRIMARY KEY (id);

GRANT ALL ON public.group_members TO anon;

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.group_members TO authenticated;

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.group_members TO service_role;

ALTER TABLE public.groups
  ADD CONSTRAINT groups_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON UPDATE CASCADE ON DELETE CASCADE;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.groups TO anon;

CREATE TABLE public.invitations (
  id           bigint                     GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at   timestamp with time zone   DEFAULT now() NOT NULL,
  group_id     uuid                       DEFAULT gen_random_uuid(),
  status       public."INVITATION_STATUS",
  member_email text
);

ALTER TABLE public.invitations
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.invitations
  ADD CONSTRAINT invitations_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.invitations
  ADD CONSTRAINT invitations_pkey PRIMARY KEY (id);

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.invitations TO anon;

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.invitations TO authenticated;

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.invitations TO service_role;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);

ALTER TABLE public.group_members
  ADD CONSTRAINT group_members_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER POLICY "Enable insert for authenticated users only" ON public.events TO PUBLIC;

ALTER POLICY "Enable insert for authenticated users only" ON public.groups TO PUBLIC;